### ISSUE TITLE
Leak

### ISSUE THREAD

**Issue by Rxxxin** [Briiqn/Ares-pvp-src#2]
Hey idk why you did that but it will be taken down

**Comment by Briiqn** [comment]
seethe + cope

**Comment by Rxxxin** [comment]
?

**Comment by Rxxxin** [comment]
i like the decompiler notices

**Comment by Briiqn** [comment]
Thx, I was too  lazy to deobf and decompile myself as I'm working on other projects atm and someone asked me for SRC so they could skid

**Comment by Briiqn** [comment]
That's why some of it is still obf xd

**Comment by Rxxxin** [comment]
You exposed yourself that you dont have a professional knowledge because the code isnt obfuscated btw

**Comment by Rxxxin** [comment]
but if smth is unobfuscated you also dont have any agreement to upload the code and to put another license on it

**Comment by Rxxxin** [comment]
> That's why some of it is still obf xd

idk why you do that but many people do that because they get a feeling of a wanna be superiority. Idk why do you think there is a obfuscation xd

**Comment by Briiqn** [comment]
1. What license was used in the client
2. Since when did I say I was a "professional"?

**Comment by Briiqn** [comment]
Also if u read the license u would see that it allows anyone to do anything with it since idrc, also I did it because I was really bored

**Comment by Briiqn** [comment]
Also yes it was retarded of me to say its obf because I didn't even check all of SRC and assumed it was still semi obf, but after checking its not, thanks for making me to use my brain!

**Comment by Rxxxin** [comment]
btw we work currently on a dmca claim i just wanted to inform you about our steps 
Its licensed after german laws we have the copyright on our code

**Comment by Rxxxin** [comment]
Have a nice day and i hope you will get more grown. I want to end our conversation because i just wanted to tell you our view of the situation. If you remove the repo we would stop our steps against you.
